import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { tmpdir } from "node:os";
import { COMMON_ALLOWED_FILES } from "../tools/artifact-audit.mjs";
import { expectedGeneratedFiles, verifyBuiltExtensionsContent, verifyGeneratedBrowserContent } from "../tools/build-output-verify.mjs";
import { ensureBuildInputFixture } from "./helpers/build-input-fixture.js";

async function write(root, path, content) {
  await mkdir(join(root, dirname(path)), { recursive: true });
  await writeFile(join(root, path), content);
}

async function withFixture(run) {
  const root = await mkdtemp(join(tmpdir(), "drop-ads-build-output-"));
  try {
    await write(root, "package.json", '{"name":"drop-ads","version":"0.1.0","type":"module"}\n');
    await write(root, "manifests/chromium.json", '{"name":"drop-ads","manifest_version":3,"background":{"service_worker":"background.js"}}\n');
    await write(root, "manifests/firefox.json", '{"name":"drop-ads","manifest_version":3,"background":{"scripts":["background.js"]}}\n');
    await write(root, "lists/default.meta.json", '{"schemaVersion":1}\n');
    await write(root, "lists/default.txt", 'block domain ads.example\n');
    await write(root, "tools/build.mjs", '// build tool fixture\n');
    await write(root, "tools/build-info.mjs", '// build info fixture\n');
    await ensureBuildInputFixture(root);

    const runtimeFiles = COMMON_ALLOWED_FILES.filter((path) =>
      path !== "build-info.json" && path !== "manifest.json" && !path.startsWith("lists/"));
    for (const path of runtimeFiles) await write(root, `src/${path}`, `source:${path}\n`);
    await write(root, "src/rules/static.json", "[]\n");

    for (const browser of ["chromium", "firefox"]) {
      const expected = await expectedGeneratedFiles(root, browser);
      for (const [path, bytes] of expected.files) await write(root, `dist/${browser}/${path}`, bytes);
    }

    await run(root);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
}

test("expected build transformation is browser-specific and deterministic", async () => {
  await withFixture(async (root) => {
    const chromium = await expectedGeneratedFiles(root, "chromium");
    const firefox = await expectedGeneratedFiles(root, "firefox");

    assert.equal(chromium.files.has("rules/static.json"), false);
    assert.equal(firefox.files.has("rules/static.json"), true);
    assert.equal(firefox.files.get("rules/static.json").toString(), "[]\n");
    assert.equal(chromium.buildInfo.sourceFingerprint, firefox.buildInfo.sourceFingerprint);

    const sourceManifest = JSON.parse(await readFile(join(root, "manifests/chromium.json"), "utf8"));
    assert.equal(
      chromium.files.get("manifest.json").toString(),
      `${JSON.stringify(sourceManifest, null, 2)}\n`
    );
  });
});

test("valid generated browser trees match current source/build transformation", async () => {
  await withFixture(async (root) => {
    const result = await verifyBuiltExtensionsContent(root);
    assert.equal(result.chromium.sourceFingerprint, result.firefox.sourceFingerprint);
    assert.ok(result.chromium.files.includes("core/runtime.js"));
    assert.ok(result.firefox.files.includes("rules/static.json"));
  });
});

for (const [label, browser, path, content] of [
  ["runtime JavaScript", "chromium", "core/runtime.js", "tampered runtime\n"],
  ["bundled list", "firefox", "lists/default.txt", "tampered list\n"],
  ["normalized manifest", "chromium", "manifest.json", '{"manifest_version":3}\n'],
  ["build identity file", "firefox", "build-info.json", '{"schemaVersion":1}\n']
]) {
  test(`generated-content verification rejects tampered ${label}`, async () => {
    await withFixture(async (root) => {
      await write(root, `dist/${browser}/${path}`, content);
      await assert.rejects(
        verifyGeneratedBrowserContent(root, browser),
        new RegExp(`${path.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`)
      );
    });
  });
}

test("changing source after build makes previously generated bytes stale", async () => {
  await withFixture(async (root) => {
    await write(root, "src/core/runtime.js", "new source runtime\n");
    const staleOutput = /(?:build-info\.json|core\/runtime\.js)/;
    await assert.rejects(verifyGeneratedBrowserContent(root, "chromium"), staleOutput);
    await assert.rejects(verifyGeneratedBrowserContent(root, "firefox"), staleOutput);
  });
});

test("browser-specific extra content fails before byte comparison", async () => {
  await withFixture(async (root) => {
    await write(root, "dist/chromium/rules/static.json", "[]\n");
    await assert.rejects(verifyGeneratedBrowserContent(root, "chromium"), /rules\/static\.json/);
  });
});
